package com.worldline.kafka.kafkamanager.dto.event;

/**
 * Event type.
 */
public enum EventType {
	LOGIN,
	CLUSTER_ADD,
	CLUSTER_EDIT,
	CLUSTER_DELETE,
	BROKER_SETTINGS_UPDATE,
	TOPIC_DELETE,
	TOPIC_CREATE,
	TOPIC_SETTINGS_UPDATE,
	TOPIC_ADD_PARTITIONS,
	TOPIC_REASSIGN_PARTITIONS,
	CONSUMER_GROUP_RESET_OFFSET,
	CONSUMER_GROUP_DELETE,
	MONITORING_ACTIVITY,
	MONITORING_LAG,
	MONITORING_NB_SERVER,
	MONITORING_NO_ACTIVITY,
	CONNECTOR_CREATE,
	CONNECTOR_UPDATE,
	CONNECTOR_RESTART,
	CONNECTOR_RESUME,
	CONNECTOR_PAUSE,
	CONNECTOR_DELETE,
	CONNECTOR_RESET_TOPICS,
	CONNECTOR_TASK_RESTART
}
